require: rubocop-rspec

RSpec/BeEql:
  Description: Check for expectations where `be(...)` can replace `eql(...)`.
  Enabled: true

RSpec/DescribeClass:
  Description: Check that the first argument to the top level describe is a constant.
  Enabled: true

RSpec/DescribedClass:
  Description: Checks that tests use `described_class`.
  SkipBlocks: false
  Enabled: true

RSpec/DescribeMethod:
  Description: Checks that the second argument to `describe` specifies a method.
  Enabled: true

RSpec/EmptyExampleGroup:
  Description: Checks if an example group does not include any tests.
  Enabled: true

RSpec/ExampleLength:
  Description: Checks for long examples.
  Enabled: true

RSpec/ExampleWording:
  Description: Checks that example descriptions do not start with "should".
  Enabled: true
  CustomTransform:
    be: is
    have: has
    not: does not
  IgnoredWords: []

RSpec/ExpectActual:
  Description: Checks for `expect(...)` calls containing literal values.
  Enabled: true

RSpec/FilePath:
  Description: Checks that spec file paths are consistent with the test subject.
  Enabled: true

RSpec/Focus:
  Description: Checks if examples are focused.
  Enabled: true

RSpec/InstanceVariable:
  Description: Checks for instance variable usage in specs.
  Enabled: true

RSpec/LeadingSubject:
  Description: Checks for `subject` definitions that come after `let` definitions.
  Enabled: true

RSpec/LetSetup:
  Description: Checks unreferenced `let!` calls being used for test setup.
  Enabled: true

RSpec/MessageExpectation:
  Description: Checks for consistent message expectation style.
  Enabled: true

RSpec/MultipleDescribes:
  Description: Checks for multiple top level describes.
  Enabled: true

RSpec/MultipleExpectations:
  Description: Checks if examples contain too many `expect` calls.
  Enabled: true

RSpec/NamedSubject:
  Description: Checks for explicitly referenced test subjects.
  Enabled: false

RSpec/NestedGroups:
  Description: Checks for nested example groups.
  Enabled: false

RSpec/NotToNot:
  Description: Checks for consistent method usage for negating expectations.
  Enabled: true
