dist: trusty
sudo: false

language: ruby
rvm:
  - 2.5

nvm:
  - 8.3.0

addons:
  chrome: stable
  postgresql: "9.6"

services:
  - postgresql
  - redis-server

# only build pushes to master, force build branches and PRs
branches:
  only:
    - master
    - /force-build$/ # allow for developers to force CI builds if required before PR

cache:
  bundler: true
  yarn: true
  directories:
    - elasticsearch-5.5.1

matrix:
  fast_finish: true

env:
  global:
    - ES_VERSION=5.5.1
    - ES_DOWNLOAD_URL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}.tar.gz

before_install:
  - gem update --system
  - gem install bundler
  - yarn install

jobs:
  include:
    - stage: test
      name: RSpec
      script: .travis/rspec

    - stage: stylistic
      name: Rubocop
      script: bundle exec rubocop

    - stage: stylistic
      name: ESLint
      script: yarn eslint app/javascript/**/*

    - stage: docs
      name: Yard
      script: bundle exec yard

    - stage: compile
      name: Frontend Assets
      script: .travis/assets
      if: branch = master AND type != pull_request
