version: "3"

services:
  postgres:
    image: "postgres:9.6-alpine"
    environment:
      POSTGRES_USER: "transientbug"
      POSTGRES_PASSWORD: "yourpassword"
    networks:
      - "services"
    volumes:
      - "postgres:/var/lib/postgresql/data"

  elasticsearch:
    image: "blacktop/elasticsearch:5.6"
    networks:
      - "services"
    volumes:
      - "elasticsearch:/usr/share/elasticsearch/data"
    healthcheck:
      #test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health", "||", "exit", "1"]
      interval: 1m
      timeout: 10s
      retries: 5

  redis:
    image: "redis:4-alpine"
    networks:
      - "services"
    volumes:
      - "redis:/data"

  sidekiq:
    depends_on:
      - "postgres"
      - "elasticsearch"
      - "redis"
    build:
      context: .
      dockerfile: Dockerfile.sidekiq
    networks:
      - "services"
    env_file:
      - ".env.production"

  clockwork:
    depends_on:
      - "postgres"
      - "elasticsearch"
      - "redis"
      - "sidekiq"
    build:
      context: .
      dockerfile: Dockerfile.clockwork
    networks:
      - "services"
    env_file:
      - ".env.production"

  rails:
    depends_on:
      - "postgres"
      - "elasticsearch"
      - "redis"
    build:
      context: .
      dockerfile: Dockerfile.rails
    ports:
      - "8000:3000"
    volumes:
      - "./storage:/dropzone"
    networks:
      - "exposed"
      - "services"
    env_file:
      - ".env.production"

  cable:
    depends_on:
      - "redis"
    build:
      context: .
      dockerfile: Dockerfile.cable
    ports:
      - "28080:28080"
    #volumes:
      #- ".:/app"
    networks:
      - "exposed"
      - "services"
    env_file:
      - ".env.production"

volumes:
  redis:
  postgres:
  elasticsearch:

networks:
  exposed:
  services:
