# fly.toml file generated for transientbug-rails on 2022-10-03T12:33:40-06:00

app = "transientbug-rails"
kill_signal = "SIGINT"
kill_timeout = 5
processes = [
  web = "bin/rails fly:server"
  worker = "bundle exec good_job start"
]

[build]
  [build.args]
    BUNDLER_VERSION = "2.3.6"
    NODE_VERSION = "16"
    RUBY_VERSION = "3.1.0"

[deploy]
  release_command = "bin/rails fly:release"

[env]
  PORT = "8080"
  SERVER_COMMAND = "bin/rails fly:server"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["web"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/"
