default: &default
  transientbug_bot:
    token: <%= Rails.application.credentials.bot_tokens[:transientbug_bot] %>
    klass: TransientBugBot

development:
  <<: *default

  transientbugDev_bot:
    token: <%= Rails.application.credentials.bot_tokens[:transientbugDev_bot] %>
    klass: TransientBugBot

test:
  <<: *default

production:
  <<: *default
