# config/chewy.yml

default: &default
  host: <%= ENV.fetch "ELASTICSEARCH_URL", "http://localhost:9200" %>

# separate environment configs
development:
  <<: *default
  prefix: 'transientbug'

test:
  <<: *default
  prefix: 'transientbug_test'

production:
  <<: *default
  prefix: "transientbug_prod"
