# config/chewy.yml
# separate environment configs
development:
  host: 'localhost:9200'
  prefix: 'transientbug'

test:
  host: 'localhost:9200'
  prefix: 'transientbug_test'

production:
  host: <%= ENV["ELASTICSEARCH_URL"] %>
  prefix: "transientbug_prod"
