name: Deploy

on:
  push:
    branches:
      - master

jobs:
  Rubocop:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - env:
          super_secret: ${{ secrets.RAILS_MASTER_KEY }}
        run: flyctl deploy
