name: Deploy

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

jobs:
  FlyioDeploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy --remote-only
