name: Specs

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

jobs:
  RSpec:
    runs-on: ubuntu-latest

    env:
      RAILS_ENV: test
      NODE_ENV: test

    services:
      postgres:
        image: postgres:10.8
        ports:
          - 5432/tcp
        env:
          POSTGRES_USER: "postgres"
          POSTGRES_PASSWORD: ""
          POSTGRES_DATABASE: "transientbug_test"

      redis:
        image: redis
        ports:
          - 6379/tcp

    steps:
      - uses: actions/checkout@v2

      - name: Install libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client libpq-dev sqlite3 libsqlite3-dev

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Setup Database
        run: |
          bundle exec rails db:prepare
        env:
          DATABASE_URL: postgresql://postgres:@localhost:${{ job.services.postgres.ports['5432'] }}/transientbug_test
          REDIS_URL: redis://localhost:${{ job.services.redis.ports['6379'] }}/0

      - name: Build Assets
        run: |
          bundle exec rake assets:precompile
        env:
          DATABASE_URL: postgresql://postgres:@localhost:${{ job.services.postgres.ports['5432'] }}/transientbug_test
          REDIS_URL: redis://localhost:${{ job.services.redis.ports['6379'] }}/0
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}

      - name: Run specs
        run: |
          bundle exec rake
        env:
          DATABASE_URL: postgresql://postgres:@localhost:${{ job.services.postgres.ports['5432'] }}/transientbug_test
          REDIS_URL: redis://localhost:${{ job.services.redis.ports['6379'] }}/0
