name: Styles

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

jobs:
  Rubocop:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Ruby 3.0.1
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.0.1

      - name: Install deps
        run: |
          gem install rubocop rubocop-rspec rubocop-rails

      - name: Run rubocop
        run: |
          rubocop

  ESLint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Node 16.10.0
        uses: actions/setup-node@v1
        with:
          node-version: 16.10.0

      - name: Install deps
        run: |
          yarn install

      - name: Run eslint
        run: |
          yarn lint
