name: Styles

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

jobs:
  Rubocop:
    runs-on: ubuntu-latest

    env:
      BUNDLE_WITHOUT: production,development,test
      BUNDLER_WITH: ci

    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run rubocop
        run: bundle exec rubocop

  ESLint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install deps
        run: yarn install

      - name: Run eslint
        run: yarn lint
