name: styles

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

jobs:
  Rubocop:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Rubocop
        uses: ./.github/actions/rubocop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ESLint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Node 12.8
        uses: actions/setup-node@v1
        with:
          node-version: 12.8.x

      - name: Install deps
        run: |
          yarn install

      - name: Run eslint
        run: |
          yarn lint
